# Generated by Django 5.2.8 on 2025-11-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_apuntes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apunte',
            name='puntuacion',
            field=models.CharField(blank=True, choices=[('5', '☆'), ('2', '☆'), ('3', '☆'), ('1', '☆'), ('4', '☆')], max_length=1, null=True),
        ),
    ]
