# Generated by Django 5.2.8 on 2025-11-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_apuntes', '0002_apunte_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='puntuacion',
            field=models.CharField(blank=True, choices=[('1', '☆'), ('5', '☆☆☆☆☆'), ('3', '☆☆☆'), ('4', '☆☆☆☆'), ('2', '☆☆')], max_length=1, null=True),
        ),
    ]
