# Generated by Django 5.2.8 on 2025-11-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_apuntes', '0003_alter_apunte_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='puntuacion',
            field=models.CharField(blank=True, choices=[('1', '☆'), ('5', '☆☆☆☆☆'), ('3', '☆☆☆'), ('2', '☆☆'), ('4', '☆☆☆☆')], max_length=5, null=True),
        ),
    ]
