# Generated by Django 5.2.8 on 2025-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_apuntes', '0004_alter_apunte_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='puntuacion',
            field=models.CharField(blank=True, choices=[('3', '☆☆☆'), ('5', '☆☆☆☆☆'), ('2', '☆☆'), ('4', '☆☆☆☆'), ('1', '☆')], max_length=6, null=True),
        ),
    ]
