# Generated by Django 5.2.8 on 2025-11-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_apuntes', '0007_alter_apunte_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apunte',
            name='puntuacion',
            field=models.CharField(blank=True, choices=[('4', '☆☆☆☆'), ('5', '☆☆☆☆☆'), ('3', '☆☆☆'), ('2', '☆☆'), ('1', '☆')], max_length=3, null=True),
        ),
    ]
