# Generated by Django 5.2.8 on 2025-11-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre', 'anio'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
    ]
