# Generated by Django 5.2.8 on 2025-11-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_materias', '0002_alter_materia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre', 'anio']},
        ),
    ]
