# Generated by Django 5.2.8 on 2025-11-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la carrera', max_length=100, verbose_name='Nombre')),
                ('universidad', models.CharField(default='UTN', help_text='Universidad a la que pertenece la carrera', max_length=100, verbose_name='Universidad')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre', 'universidad'],
            },
        ),
    ]
