# Generated by Django 5.2.8 on 2025-11-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_carreras', '0001_initial'),
        ('gestion_materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'ordering': ['nombre', 'universidad']},
        ),
        migrations.AddField(
            model_name='carrera',
            name='materias',
            field=models.ManyToManyField(related_name='carrera', to='gestion_materias.materia'),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='universidad',
            field=models.CharField(default='UTN', max_length=100),
        ),
    ]
