# Generated by Django 5.2.8 on 2025-11-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_carreras', '0002_alter_carrera_options_carrera_materias_and_more'),
        ('gestion_materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='materias',
            field=models.ManyToManyField(related_name='carreras', to='gestion_materias.materia'),
        ),
    ]
